# Generated by Django 3.2.6 on 2021-08-06 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Custom_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('type_of', models.CharField(choices=[('OWN', 'Owner'), ('DEV', 'Developer')], default='DEV', max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dp')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StartUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('requirement', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup_listing.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Text_field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup_listing.custom_form')),
            ],
        ),
        migrations.CreateModel(
            name='StartUpImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='startup_images')),
                ('start_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup_listing.startup')),
            ],
        ),
        migrations.CreateModel(
            name='Startup_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('project_details', models.TextField()),
                ('time', models.DateField(auto_now_add=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup_listing.startup')),
                ('tags', models.ManyToManyField(related_name='project_tags', to='startup_listing.Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup_listing.startup_project')),
            ],
        ),
        migrations.CreateModel(
            name='Phone_field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup_listing.custom_form')),
            ],
        ),
        migrations.CreateModel(
            name='Int_field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('integer', models.IntegerField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup_listing.custom_form')),
            ],
        ),
        migrations.CreateModel(
            name='File_field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('file_in', models.FileField(upload_to='FileField')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup_listing.custom_form')),
            ],
        ),
        migrations.CreateModel(
            name='Email_field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup_listing.custom_form')),
            ],
        ),
        migrations.AddField(
            model_name='custom_form',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup_listing.profile'),
        ),
        migrations.AddField(
            model_name='custom_form',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup_listing.startup_project'),
        ),
        migrations.CreateModel(
            name='Char_field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('character', models.CharField(max_length=300)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup_listing.custom_form')),
            ],
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup_listing.startup_project')),
            ],
        ),
    ]
