# Generated by Django 3.2.6 on 2021-08-06 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startup_listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup_project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startup_listing.category'),
        ),
    ]
