# Generated by Django 3.2.6 on 2021-08-06 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup_listing', '0002_startup_project_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_form',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='custom_form',
            name='project',
        ),
        migrations.RemoveField(
            model_name='email_field',
            name='form',
        ),
        migrations.RemoveField(
            model_name='file_field',
            name='form',
        ),
        migrations.RemoveField(
            model_name='int_field',
            name='form',
        ),
        migrations.RemoveField(
            model_name='phone_field',
            name='form',
        ),
        migrations.RemoveField(
            model_name='text_field',
            name='form',
        ),
        migrations.DeleteModel(
            name='Char_field',
        ),
        migrations.DeleteModel(
            name='Custom_Form',
        ),
        migrations.DeleteModel(
            name='Email_field',
        ),
        migrations.DeleteModel(
            name='File_field',
        ),
        migrations.DeleteModel(
            name='Int_field',
        ),
        migrations.DeleteModel(
            name='Phone_field',
        ),
        migrations.DeleteModel(
            name='Text_field',
        ),
    ]
