# Generated by Django 3.2.6 on 2021-08-06 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startup_listing', '0003_auto_20210806_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_Of_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=300)),
                ('type_of', models.CharField(choices=[('CF', 'Character Filed'), ('TF', 'Text Field'), ('FF', 'File Field'), ('IF', 'Integer Field'), ('EF', 'Email Field'), ('PF', 'Phone Field')], default='CR', max_length=2)),
                ('project_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup_listing.startup_project')),
            ],
        ),
        migrations.CreateModel(
            name='Form_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field', models.CharField(blank=True, max_length=300, null=True)),
                ('text_field', models.TextField(blank=True, null=True)),
                ('int_field', models.IntegerField(blank=True, null=True)),
                ('file_field', models.FileField(blank=True, null=True, upload_to='field_file')),
                ('email_field', models.EmailField(max_length=254)),
                ('phone_field', models.BigIntegerField()),
                ('field_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup_listing.type_of_field')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup_listing.profile')),
                ('project_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup_listing.startup_project')),
            ],
        ),
    ]
