# Generated by Django 3.2.6 on 2021-08-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup_listing', '0007_community_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup_project',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
