# Generated by Django 3.2.6 on 2021-08-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup_listing', '0008_alter_startup_project_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='requirement',
        ),
        migrations.AddField(
            model_name='startup_project',
            name='requirement',
            field=models.TextField(default=''),
        ),
    ]
