# Generated by Django 3.2.6 on 2021-08-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup_listing', '0009_auto_20210807_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
