# Generated by Django 3.2.6 on 2021-08-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup_listing', '0019_auto_20210811_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup_project',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to='startup_listing.Profile'),
        ),
    ]
