# Generated by Django 3.2.6 on 2021-08-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup_listing', '0020_startup_project_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_of_field',
            name='type_of',
            field=models.CharField(choices=[('CF', 'Character Filed'), ('TF', 'Text Field'), ('FF', 'File Field'), ('IF', 'Integer Field')], default='CF', max_length=2),
        ),
    ]
