# Generated by Django 3.2.6 on 2021-08-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup_listing', '0021_alter_type_of_field_type_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup_project',
            name='approved_participants',
            field=models.ManyToManyField(related_name='approved_participants', to='startup_listing.Profile'),
        ),
    ]
