# Generated by Django 3.2.6 on 2021-08-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup_listing', '0022_startup_project_approved_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_field',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
