# Generated by Django 3.2.6 on 2021-08-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup_listing', '0023_form_field_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup_project',
            name='approved_participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='approved_participants', to='startup_listing.Profile'),
        ),
        migrations.AlterField(
            model_name='startup_project',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='participants', to='startup_listing.Profile'),
        ),
    ]
