# Generated by Django 3.2.6 on 2021-08-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup_listing', '0024_auto_20210812_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='startup_listing.Tags'),
        ),
    ]
