# Generated by Django 3.2.6 on 2021-08-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup_listing', '0025_profile_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type_of',
            field=models.CharField(blank=True, choices=[('OWN', 'Owner'), ('DEV', 'Developer')], max_length=3, null=True),
        ),
    ]
