# Generated by Django 3.2.6 on 2021-08-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup_listing', '0026_alter_profile_type_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefit',
            name='project',
        ),
        migrations.AddField(
            model_name='benefit',
            name='project',
            field=models.ManyToManyField(to='startup_listing.Startup_Project'),
        ),
    ]
